<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="CalculatorTest-20170605124631" tests="2" time="0.001">
	<testcase classname="CalculatorTest" name="test_add" time="0.000">
		<error message="name 'number1' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "unit_test.py", line 19, in test_add
    value = self.calc.add(number1, number2)
NameError: name 'number1' is not defined
]]>		</error>
	</testcase>
	<testcase classname="CalculatorTest" name="test_subtract" time="0.000">
		<error message="name 'number1' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "unit_test.py", line 25, in test_subtract
    value = self.calc.subtract(number1, number2)
NameError: name 'number1' is not defined
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
